test:	1 2 3 4 5
1:
	../hanando -f -cpp test1.cpp > test1.s
	gcc -g test1.s -o test1
	./test1
2:
	../hanando -f -cpp test2.cpp > test2.s
	gcc -g test2.s -o test2
	./test2
3:
	../hanando -f -cpp test3.cpp > test3.s
	gcc -g test3.s -o test3
	./test3
4:
	../hanando -f -cpp test4.cpp > test4.s
	gcc -g test4.s -o test4
	./test4
5:
	../hanando -f -cpp test5.cpp > test5.s
	gcc -g test5.s -o test5
	./test5
